# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3724dd7a289c9ad81f683ce7c5f1f31"
name = "orders-management-app"
handle = "orders-management-app-1"
application_url = "https://heart-peak-consideration-cassette.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "minh-nguyen-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://heart-peak-consideration-cassette.trycloudflare.com/auth/callback",
  "https://heart-peak-consideration-cassette.trycloudflare.com/auth/shopify/callback",
  "https://heart-peak-consideration-cassette.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "orders/create", "orders/edited" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/edited" ]
  uri = "https://webhook.site/b01b6e7a-6dd5-402e-b19f-60ce4b81c524"

[pos]
embedded = false
