# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3724dd7a289c9ad81f683ce7c5f1f31"
name = "orders-management-app"
handle = "orders-management-app-1"
application_url = "https://plays-scenes-implementing-dangerous.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "minh-nguyen-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://plays-scenes-implementing-dangerous.trycloudflare.com/auth/callback",
  "https://plays-scenes-implementing-dangerous.trycloudflare.com/auth/shopify/callback",
  "https://plays-scenes-implementing-dangerous.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "orders/create", "orders/updated" ]
  uri = "/webhooks" # using the relative URL "/webhooks" because app URL will update every time you run shopify app dev

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/updated" ]
  uri = "https://webhook.site/2abf2500-131d-486a-94fb-687dfbc7da9a"

[pos]
embedded = false
